---
 - name: Setup Apache and PHP
   hosts: 127.0.0.1
   connection: local
   become: true

   tasks: 
    - name: Install Apache and PHP
      apt: 
       name: 
        - apache2
        - libapache2-mod-php7.4
        - php7.4
       state: present 
       update_cache: yes

    - name: Ensure Apache is running
      systemd: 
       name: apache2
       state: started
       enabled: yes
      
    - name: Enable PHP 7.4 module
      command: a2enmod php7.4
      notify: Restart Apache

    - name: Remove default index.html
      file: 
        path: /var/www/html/index.html
        state: absent

    - name: Deploy index.php 
      copy: 
         dest: /var/www/html/index.php
         content: |
          <?php
          date_default_timezone_set("Africa/Lagos");
          echo "Current time: "  . date("F d, Y h:i:s A e");
          ?>

   handlers:
      - name: Restart Apache
        service: 
          name: apache2
          state: restarted 


